development:
  adapter: mysql
  encoding: utf8
  database: towel_development
  username: root
  password:
  host: localhost
  # adapter: sqlite3
  # dbfile: db/sqlite3/development.db

test:
  adapter: mysql
  encoding: utf8
  database: towel_test
  username: root
  password:
  host: localhost
  # adapter: sqlite3
  # dbfile: db/sqlite3/development.db
